local Rayfield = loadstring(game:HttpGet("https://sirius.menu/rayfield"))()

local Window = Rayfield:CreateWindow({
    Name = "Jual Jeruk",
    LoadingTitle = "Auto Purchase",
    LoadingSubtitle = "Tycoon 1-50",
    ConfigurationSaving = { Enabled = false },
    Discord = { Enabled = false },
    KeySystem = false,
})

local Tab = Window:CreateTab("Auto Purchase", 4483362458)

local running = false
local ws = game:GetService("Workspace")

Tab:CreateToggle({
    Name = "Auto Purchase",
    CurrentValue = false,
    Flag = "TogglePurchase",
    Callback = function(Value)
        running = Value
        if running then
            Rayfield:Notify({ Title = "ON", Content = "Auto Purchase jalan!", Duration = 2 })
            task.spawn(function()
                while running do
                    for i = 1, 50 do
        pcall(function() ws["Tycoon"..i].Purchases.Hills.Buttons.Roads["Republic Road"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Hills.Buttons["Hill 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Fence"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Garage Door 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Garage Door 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Garage Door 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Path"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Roof"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Decor["Dash Windows"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.LemonDash.Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["Company Vehicle"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["Dash Exterior Sign"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["Influencer Collabs"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["LemonDash Plus"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Multiplier["Special Deals"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonDash.Buttons.Structure["Dash Walls"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Airlock Doors 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Airlock Doors 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Containers 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Containers 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crate Dock 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crate Dock 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crates 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crates 4"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Crates 5"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Edge Lines"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Neon Wall Trim"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Rear Edge Lines"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Decor["X Rear Path Guide"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Agriculture Expansion"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Interdimensional Markets"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Intergalactic Lemon Trade"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Lemon Cryo Storage"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Lemon Teleportation"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Quantum Lemon Tech"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Sentient Lemons"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Space Agriculture"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["Warp Speed Shipping"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Multiplier["X Exterior Signs"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Rear Platform 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Rear Platform 4"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Rear Platform 5"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Wall Base"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.LemonX.Buttons.Structure["X Walls 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Minigames.Buttons["Minigame Trade"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Decor["Staircase Step 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Decor["Staircase Step 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Decor["Staircase Step 5"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Decor["Staircase Step 8"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Depot Statue Major"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Depot Statue Minor 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Republic Statue Major"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Republic Statue Minor 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Robotics Statue Minor 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Stand Statue Major"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Stand Statue Minor 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Trading Statue Major"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Multiplier["Trading Statue Minor 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 6"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 7"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Curve 8"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Intro"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Platform 4"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Platform 7"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases.Staircase.Buttons.Structure["Staircase Platform Final"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Cars"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Ceiling Lights"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Exterior Ladder"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Fence"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Garage Door 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Office Lights"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Office Plants"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Roof"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Sign 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Sign 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Speed Bump 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Decor["Depot Walls 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier.Turbochargers.Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Bigger Fleet"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Citrus Fuel Lines"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Even Bigger Fleet"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Lemon Commercials"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Toll Evasion"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Truck Branding"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Multiplier["Wholesale Pricing"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Structure["Depot Foundation"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Structure["Depot Office Floor"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Structure["Depot Raised Area"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Depot"].Buttons.Structure["Depot Roof Framing"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Cars"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Entry Plants"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Entry"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Lounge Area"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Lower Lights"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Roof Door"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Room 2 Door"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Room 3 Door"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Second Floor Lights"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Second Floor Windows"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Decor["Labs Windows"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Citrus Based Fuel"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Climate Control"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Fuel Deliveries"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Labs Exterior Sign"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Lemon Reactor"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Multipliers["Nano Tech"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Balcony"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Ladder"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Room 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Testing Area"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Walls 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Walls 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Labs"].Buttons.Structure["Labs Walls Detailing"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Balcony Door"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Curbs"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 1 Plants"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 2 Lighting"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 2 Plants 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 2 Windows"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 3 Lighting"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Floor 3 Staircase 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Greenery 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Inner Statue 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Inner Statue 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Painting 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Parked Cars"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Red Carpet"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Skylight"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Decor["Republic Welcome Sign"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Bank Expansion"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Centralized Power"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Lemon Propaganda"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Lemon Subsidies"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Lemon Tariffs"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Lemon Tax"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Personal Aides"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Public Citrus Works"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Multiplier["Reduced Regulation"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Other["Republic Manager"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Balcony"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Building 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Building 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Courtyard"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 2 Left"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 2 Staircase 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 2 Walls"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 3 Walls"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Floor 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Front Pillars 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Rear Pillar 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Rear Pillar 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons.Structure["Republic Roof"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Republic"].Buttons["Lemon Republic"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Cars"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Curbs 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Curbs 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Curbs 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Entry Lighting"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Greenery 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Greenery 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Lighting 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Mega Door"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Parking Lot"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Railings 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Railings 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Decor["Robotics Staircase 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Citrus Lubricant"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Cyber Lemons"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Lemon Domination"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Military Contracts"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Nanobot Farm"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Overseas Production"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Robot Employees"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Robot Overclocking"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Multiplier["Robotics Exterior Signs"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Structure["Robotics Balcony 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Robotics"].Buttons.Structure["Robotics Balcony 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Stand"].Buttons.Multiplier["Ice Maker"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Stand"].Buttons.Multiplier["Street Fliers"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Stand"].Buttons.Multiplier["Sugar Mixer"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Stand"].Buttons["Lemon Stand"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Floor 1 Lights"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Floor 1 Windows"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Floor 2 Windows"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Floor 3 Windows"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Greenery"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Roof"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Decor["Trading Sign"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["24 Hour Trading"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Go Public"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Lemon NFTs"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Obfuscated Finances"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Offshore Banking"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Multiplier["Trading Exterior Displays"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Other["Trading Manager"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Structure["Trading Lot"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons.Structure["Trading Roof Supports"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["Lemon Trading"].Buttons["Lemon Trading"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Fence 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Fence 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Gate Barrier Arm"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Ground Containers 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Ground Containers 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Ground Containers 3"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Loose Scaffolding"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Road Curbs"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Truck 1"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Truck 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Decor["X Van"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Control Lights"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Launch Surface"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Launchpad"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Rocket Lift"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Scaffolding 2"].Purchase:InvokeServer(false) end)
        pcall(function() ws["Tycoon"..i].Purchases["LemonX Ground"].Buttons.Structure["X Scaffolding 3"].Purchase:InvokeServer(false) end)
                    end
                    task.wait()
                end
            end)
        else
            Rayfield:Notify({ Title = "OFF", Content = "Auto Purchase berhenti.", Duration = 2 })
        end
    end,
})
